import type { Metadata } from "next";
import {Noto_Sans_KR} from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";

const font = Noto_Sans_KR({
  weight: "300",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body
        className={`${font.className} min-h-dvh`}
      >
      <Header />
        {children}
      </body>
    </html>
  );
}
